EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr A3 16535 11693
encoding utf-8
Sheet 1 1
Title ""
Date "2021-03-12 22:09"
Rev ""
Comp ""
Comment1 "Author: "
Comment2 "Generated by klepcbgen.py v0.1"
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L Switch:SW_Push K0
U 1 1 00000000
P 1200 1050
F 0 "K0" H 1200 1283 60  0000 C CNN
F 1 "KEYSW" H 1200 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 1200 1050 60  0001 C CNN
F 3 "" H 1200 1050 60  0000 C CNN
	1    1200 1050
	1    0    0    -1  
$EndComp
Text Label 1400 1350 0    50   ~ 0
Row_4
Text Label 1000 1050 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K1
U 1 1 604C45CE
P 2400 1050
F 0 "K1" H 2400 1283 60  0000 C CNN
F 1 "KEYSW" H 2400 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2400 1050 60  0001 C CNN
F 3 "" H 2400 1050 60  0000 C CNN
	1    2400 1050
	1    0    0    -1  
$EndComp
Text Label 2600 1350 0    50   ~ 0
Row_1
Text Label 2200 1050 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K2
U 1 1 604C45D1
P 3200 1050
F 0 "K2" H 3200 1283 60  0000 C CNN
F 1 "KEYSW" H 3200 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3200 1050 60  0001 C CNN
F 3 "" H 3200 1050 60  0000 C CNN
	1    3200 1050
	1    0    0    -1  
$EndComp
Text Label 3400 1350 0    50   ~ 0
Row_1
Text Label 3000 1050 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K3
U 1 1 604C45D6
P 4000 1050
F 0 "K3" H 4000 1283 60  0000 C CNN
F 1 "KEYSW" H 4000 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4000 1050 60  0001 C CNN
F 3 "" H 4000 1050 60  0000 C CNN
	1    4000 1050
	1    0    0    -1  
$EndComp
Text Label 4200 1350 0    50   ~ 0
Row_6
Text Label 3800 1050 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K4
U 1 1 604C45BC
P 4800 1050
F 0 "K4" H 4800 1283 60  0000 C CNN
F 1 "KEYSW" H 4800 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4800 1050 60  0001 C CNN
F 3 "" H 4800 1050 60  0000 C CNN
	1    4800 1050
	1    0    0    -1  
$EndComp
Text Label 5000 1350 0    50   ~ 0
Row_4
Text Label 4600 1050 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K5
U 1 1 604C45C0
P 6000 1050
F 0 "K5" H 6000 1283 60  0000 C CNN
F 1 "KEYSW" H 6000 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6000 1050 60  0001 C CNN
F 3 "" H 6000 1050 60  0000 C CNN
	1    6000 1050
	1    0    0    -1  
$EndComp
Text Label 6200 1350 0    50   ~ 0
Row_0
Text Label 5800 1050 2    50   ~ 0
Col_5
$Comp
L Switch:SW_Push K6
U 1 1 604C45C7
P 6800 1050
F 0 "K6" H 6800 1283 60  0000 C CNN
F 1 "KEYSW" H 6800 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6800 1050 60  0001 C CNN
F 3 "" H 6800 1050 60  0000 C CNN
	1    6800 1050
	1    0    0    -1  
$EndComp
Text Label 7000 1350 0    50   ~ 0
Row_4
Text Label 6600 1050 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K7
U 1 1 604C45CC
P 7600 1050
F 0 "K7" H 7600 1283 60  0000 C CNN
F 1 "KEYSW" H 7600 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7600 1050 60  0001 C CNN
F 3 "" H 7600 1050 60  0000 C CNN
	1    7600 1050
	1    0    0    -1  
$EndComp
Text Label 7800 1350 0    50   ~ 0
Row_6
Text Label 7400 1050 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K8
U 1 1 604C45CB
P 8400 1050
F 0 "K8" H 8400 1283 60  0000 C CNN
F 1 "KEYSW" H 8400 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8400 1050 60  0001 C CNN
F 3 "" H 8400 1050 60  0000 C CNN
	1    8400 1050
	1    0    0    -1  
$EndComp
Text Label 8600 1350 0    50   ~ 0
Row_1
Text Label 8200 1050 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K9
U 1 1 604C45C8
P 9600 1050
F 0 "K9" H 9600 1283 60  0000 C CNN
F 1 "KEYSW" H 9600 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9600 1050 60  0001 C CNN
F 3 "" H 9600 1050 60  0000 C CNN
	1    9600 1050
	1    0    0    -1  
$EndComp
Text Label 9800 1350 0    50   ~ 0
Row_1
Text Label 9400 1050 2    50   ~ 0
Col_2
$Comp
L Switch:SW_Push K10
U 1 1 604C45C6
P 10400 1050
F 0 "K10" H 10400 1283 60  0000 C CNN
F 1 "KEYSW" H 10400 950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10400 1050 60  0001 C CNN
F 3 "" H 10400 1050 60  0000 C CNN
	1    10400 1050
	1    0    0    -1  
$EndComp
Text Label 10600 1350 0    50   ~ 0
Row_0
Text Label 10200 1050 2    50   ~ 0
Col_2
$Comp
L Switch:SW_Push K11
U 1 1 604C45BA
P 1200 1550
F 0 "K11" H 1200 1783 60  0000 C CNN
F 1 "KEYSW" H 1200 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 1200 1550 60  0001 C CNN
F 3 "" H 1200 1550 60  0000 C CNN
	1    1200 1550
	1    0    0    -1  
$EndComp
Text Label 1400 1850 0    50   ~ 0
Row_1
Text Label 1000 1550 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K12
U 1 1 604C45C2
P 2000 1550
F 0 "K12" H 2000 1783 60  0000 C CNN
F 1 "KEYSW" H 2000 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2000 1550 60  0001 C CNN
F 3 "" H 2000 1550 60  0000 C CNN
	1    2000 1550
	1    0    0    -1  
$EndComp
Text Label 2200 1850 0    50   ~ 0
Row_0
Text Label 1800 1550 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K13
U 1 1 604C45BF
P 2800 1550
F 0 "K13" H 2800 1783 60  0000 C CNN
F 1 "KEYSW" H 2800 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2800 1550 60  0001 C CNN
F 3 "" H 2800 1550 60  0000 C CNN
	1    2800 1550
	1    0    0    -1  
$EndComp
Text Label 3000 1850 0    50   ~ 0
Row_0
Text Label 2600 1550 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K14
U 1 1 604C45BD
P 3600 1550
F 0 "K14" H 3600 1783 60  0000 C CNN
F 1 "KEYSW" H 3600 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3600 1550 60  0001 C CNN
F 3 "" H 3600 1550 60  0000 C CNN
	1    3600 1550
	1    0    0    -1  
$EndComp
Text Label 3800 1850 0    50   ~ 0
Row_0
Text Label 3400 1550 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K15
U 1 1 604C45BB
P 4400 1550
F 0 "K15" H 4400 1783 60  0000 C CNN
F 1 "KEYSW" H 4400 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4400 1550 60  0001 C CNN
F 3 "" H 4400 1550 60  0000 C CNN
	1    4400 1550
	1    0    0    -1  
$EndComp
Text Label 4600 1850 0    50   ~ 0
Row_0
Text Label 4200 1550 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K16
U 1 1 604C45D9
P 5200 1550
F 0 "K16" H 5200 1783 60  0000 C CNN
F 1 "KEYSW" H 5200 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 5200 1550 60  0001 C CNN
F 3 "" H 5200 1550 60  0000 C CNN
	1    5200 1550
	1    0    0    -1  
$EndComp
Text Label 5400 1850 0    50   ~ 0
Row_1
Text Label 5000 1550 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K17
U 1 1 604C45D7
P 6000 1550
F 0 "K17" H 6000 1783 60  0000 C CNN
F 1 "KEYSW" H 6000 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6000 1550 60  0001 C CNN
F 3 "" H 6000 1550 60  0000 C CNN
	1    6000 1550
	1    0    0    -1  
$EndComp
Text Label 6200 1850 0    50   ~ 0
Row_1
Text Label 5800 1550 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K18
U 1 1 604C45CD
P 6800 1550
F 0 "K18" H 6800 1783 60  0000 C CNN
F 1 "KEYSW" H 6800 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6800 1550 60  0001 C CNN
F 3 "" H 6800 1550 60  0000 C CNN
	1    6800 1550
	1    0    0    -1  
$EndComp
Text Label 7000 1850 0    50   ~ 0
Row_0
Text Label 6600 1550 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K19
U 1 1 604C45D2
P 7600 1550
F 0 "K19" H 7600 1783 60  0000 C CNN
F 1 "KEYSW" H 7600 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7600 1550 60  0001 C CNN
F 3 "" H 7600 1550 60  0000 C CNN
	1    7600 1550
	1    0    0    -1  
$EndComp
Text Label 7800 1850 0    50   ~ 0
Row_0
Text Label 7400 1550 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K20
U 1 1 604C45CF
P 8400 1550
F 0 "K20" H 8400 1783 60  0000 C CNN
F 1 "KEYSW" H 8400 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8400 1550 60  0001 C CNN
F 3 "" H 8400 1550 60  0000 C CNN
	1    8400 1550
	1    0    0    -1  
$EndComp
Text Label 8600 1850 0    50   ~ 0
Row_0
Text Label 8200 1550 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K21
U 1 1 604C45D3
P 9200 1550
F 0 "K21" H 9200 1783 60  0000 C CNN
F 1 "KEYSW" H 9200 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9200 1550 60  0001 C CNN
F 3 "" H 9200 1550 60  0000 C CNN
	1    9200 1550
	1    0    0    -1  
$EndComp
Text Label 9400 1850 0    50   ~ 0
Row_0
$Comp
L Switch:SW_Push K22
U 1 1 604C45C3
P 10000 1550
F 0 "K22" H 10000 1783 60  0000 C CNN
F 1 "KEYSW" H 10000 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10000 1550 60  0001 C CNN
F 3 "" H 10000 1550 60  0000 C CNN
	1    10000 1550
	1    0    0    -1  
$EndComp
Text Label 10200 1850 0    50   ~ 0
Row_1
Text Label 9800 1550 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K23
U 1 1 604C45A2
P 10800 1550
F 0 "K23" H 10800 1783 60  0000 C CNN
F 1 "KEYSW" H 10800 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10800 1550 60  0001 C CNN
F 3 "" H 10800 1550 60  0000 C CNN
	1    10800 1550
	1    0    0    -1  
$EndComp
Text Label 11000 1850 0    50   ~ 0
Row_1
Text Label 10600 1550 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K24
U 1 1 604C45A1
P 12000 1550
F 0 "K24" H 12000 1783 60  0000 C CNN
F 1 "KEYSW" H 12000 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_2.00u_PCB" H 12000 1550 60  0001 C CNN
F 3 "" H 12000 1550 60  0000 C CNN
	1    12000 1550
	1    0    0    -1  
$EndComp
Text Label 12200 1850 0    50   ~ 0
Row_6
Text Label 11800 1550 2    50   ~ 0
Col_2
$Comp
L Switch:SW_Push K25
U 1 1 604C459F
P 13200 1550
F 0 "K25" H 13200 1783 60  0000 C CNN
F 1 "KEYSW" H 13200 1450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 13200 1550 60  0001 C CNN
F 3 "" H 13200 1550 60  0000 C CNN
	1    13200 1550
	1    0    0    -1  
$EndComp
Text Label 13400 1850 0    50   ~ 0
Row_3
$Comp
L Switch:SW_Push K26
U 1 1 604C45AF
P 1400 2050
F 0 "K26" H 1400 2283 60  0000 C CNN
F 1 "KEYSW" H 1400 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.50u_PCB" H 1400 2050 60  0001 C CNN
F 3 "" H 1400 2050 60  0000 C CNN
	1    1400 2050
	1    0    0    -1  
$EndComp
Text Label 1600 2350 0    50   ~ 0
Row_6
Text Label 1200 2050 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K27
U 1 1 604C459D
P 2400 2050
F 0 "K27" H 2400 2283 60  0000 C CNN
F 1 "KEYSW" H 2400 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2400 2050 60  0001 C CNN
F 3 "" H 2400 2050 60  0000 C CNN
	1    2400 2050
	1    0    0    -1  
$EndComp
Text Label 2600 2350 0    50   ~ 0
Row_7
Text Label 2200 2050 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K28
U 1 1 604C459C
P 3200 2050
F 0 "K28" H 3200 2283 60  0000 C CNN
F 1 "KEYSW" H 3200 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3200 2050 60  0001 C CNN
F 3 "" H 3200 2050 60  0000 C CNN
	1    3200 2050
	1    0    0    -1  
$EndComp
Text Label 3400 2350 0    50   ~ 0
Row_7
Text Label 3000 2050 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K29
U 1 1 604C459A
P 4000 2050
F 0 "K29" H 4000 2283 60  0000 C CNN
F 1 "KEYSW" H 4000 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4000 2050 60  0001 C CNN
F 3 "" H 4000 2050 60  0000 C CNN
	1    4000 2050
	1    0    0    -1  
$EndComp
Text Label 4200 2350 0    50   ~ 0
Row_7
Text Label 3800 2050 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K30
U 1 1 604C458D
P 4800 2050
F 0 "K30" H 4800 2283 60  0000 C CNN
F 1 "KEYSW" H 4800 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4800 2050 60  0001 C CNN
F 3 "" H 4800 2050 60  0000 C CNN
	1    4800 2050
	1    0    0    -1  
$EndComp
Text Label 5000 2350 0    50   ~ 0
Row_7
Text Label 4600 2050 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K31
U 1 1 604C4597
P 5600 2050
F 0 "K31" H 5600 2283 60  0000 C CNN
F 1 "KEYSW" H 5600 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 5600 2050 60  0001 C CNN
F 3 "" H 5600 2050 60  0000 C CNN
	1    5600 2050
	1    0    0    -1  
$EndComp
Text Label 5800 2350 0    50   ~ 0
Row_6
Text Label 5400 2050 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K32
U 1 1 604C4596
P 6400 2050
F 0 "K32" H 6400 2283 60  0000 C CNN
F 1 "KEYSW" H 6400 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6400 2050 60  0001 C CNN
F 3 "" H 6400 2050 60  0000 C CNN
	1    6400 2050
	1    0    0    -1  
$EndComp
Text Label 6600 2350 0    50   ~ 0
Row_6
Text Label 6200 2050 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K33
U 1 1 604C4594
P 7200 2050
F 0 "K33" H 7200 2283 60  0000 C CNN
F 1 "KEYSW" H 7200 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7200 2050 60  0001 C CNN
F 3 "" H 7200 2050 60  0000 C CNN
	1    7200 2050
	1    0    0    -1  
$EndComp
Text Label 7400 2350 0    50   ~ 0
Row_7
Text Label 7000 2050 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K34
U 1 1 604C4593
P 8000 2050
F 0 "K34" H 8000 2283 60  0000 C CNN
F 1 "KEYSW" H 8000 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8000 2050 60  0001 C CNN
F 3 "" H 8000 2050 60  0000 C CNN
	1    8000 2050
	1    0    0    -1  
$EndComp
Text Label 8200 2350 0    50   ~ 0
Row_7
Text Label 7800 2050 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K35
U 1 1 604C4591
P 8800 2050
F 0 "K35" H 8800 2283 60  0000 C CNN
F 1 "KEYSW" H 8800 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8800 2050 60  0001 C CNN
F 3 "" H 8800 2050 60  0000 C CNN
	1    8800 2050
	1    0    0    -1  
$EndComp
Text Label 9000 2350 0    50   ~ 0
Row_7
Text Label 8600 2050 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K36
U 1 1 604C4590
P 9600 2050
F 0 "K36" H 9600 2283 60  0000 C CNN
F 1 "KEYSW" H 9600 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9600 2050 60  0001 C CNN
F 3 "" H 9600 2050 60  0000 C CNN
	1    9600 2050
	1    0    0    -1  
$EndComp
Text Label 9800 2350 0    50   ~ 0
Row_7
Text Label 9400 2050 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K37
U 1 1 604C458E
P 10400 2050
F 0 "K37" H 10400 2283 60  0000 C CNN
F 1 "KEYSW" H 10400 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10400 2050 60  0001 C CNN
F 3 "" H 10400 2050 60  0000 C CNN
	1    10400 2050
	1    0    0    -1  
$EndComp
Text Label 10600 2350 0    50   ~ 0
Row_6
Text Label 10200 2050 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K38
U 1 1 604C4599
P 11200 2050
F 0 "K38" H 11200 2283 60  0000 C CNN
F 1 "KEYSW" H 11200 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 11200 2050 60  0001 C CNN
F 3 "" H 11200 2050 60  0000 C CNN
	1    11200 2050
	1    0    0    -1  
$EndComp
Text Label 11400 2350 0    50   ~ 0
Row_6
Text Label 11000 2050 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K39
U 1 1 604C45B8
P 12200 2050
F 0 "K39" H 12200 2283 60  0000 C CNN
F 1 "KEYSW" H 12200 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.50u_PCB" H 12200 2050 60  0001 C CNN
F 3 "" H 12200 2050 60  0000 C CNN
	1    12200 2050
	1    0    0    -1  
$EndComp
Text Label 12400 2350 0    50   ~ 0
Row_5
Text Label 12000 2050 2    50   ~ 0
Col_2
$Comp
L Switch:SW_Push K40
U 1 1 604C45B7
P 13200 2050
F 0 "K40" H 13200 2283 60  0000 C CNN
F 1 "KEYSW" H 13200 1950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 13200 2050 60  0001 C CNN
F 3 "" H 13200 2050 60  0000 C CNN
	1    13200 2050
	1    0    0    -1  
$EndComp
Text Label 13400 2350 0    50   ~ 0
Row_1
Text Label 13000 2050 2    50   ~ 0
Col_0
$Comp
L Switch:SW_Push K41
U 1 1 604C45B5
P 1500 2550
F 0 "K41" H 1500 2783 60  0000 C CNN
F 1 "KEYSW" H 1500 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.75u_PCB" H 1500 2550 60  0001 C CNN
F 3 "" H 1500 2550 60  0000 C CNN
	1    1500 2550
	1    0    0    -1  
$EndComp
Text Label 1700 2850 0    50   ~ 0
Row_6
Text Label 1300 2550 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K42
U 1 1 604C45B4
P 2600 2550
F 0 "K42" H 2600 2783 60  0000 C CNN
F 1 "KEYSW" H 2600 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2600 2550 60  0001 C CNN
F 3 "" H 2600 2550 60  0000 C CNN
	1    2600 2550
	1    0    0    -1  
$EndComp
Text Label 2800 2850 0    50   ~ 0
Row_5
Text Label 2400 2550 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K43
U 1 1 604C45B2
P 3400 2550
F 0 "K43" H 3400 2783 60  0000 C CNN
F 1 "KEYSW" H 3400 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3400 2550 60  0001 C CNN
F 3 "" H 3400 2550 60  0000 C CNN
	1    3400 2550
	1    0    0    -1  
$EndComp
Text Label 3600 2850 0    50   ~ 0
Row_5
Text Label 3200 2550 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K44
U 1 1 604C45B1
P 4200 2550
F 0 "K44" H 4200 2783 60  0000 C CNN
F 1 "KEYSW" H 4200 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4200 2550 60  0001 C CNN
F 3 "" H 4200 2550 60  0000 C CNN
	1    4200 2550
	1    0    0    -1  
$EndComp
Text Label 4400 2850 0    50   ~ 0
Row_5
Text Label 4000 2550 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K45
U 1 1 604C45A4
P 5000 2550
F 0 "K45" H 5000 2783 60  0000 C CNN
F 1 "KEYSW" H 5000 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 5000 2550 60  0001 C CNN
F 3 "" H 5000 2550 60  0000 C CNN
	1    5000 2550
	1    0    0    -1  
$EndComp
Text Label 5200 2850 0    50   ~ 0
Row_5
Text Label 4800 2550 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K46
U 1 1 604C45AE
P 5800 2550
F 0 "K46" H 5800 2783 60  0000 C CNN
F 1 "KEYSW" H 5800 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 5800 2550 60  0001 C CNN
F 3 "" H 5800 2550 60  0000 C CNN
	1    5800 2550
	1    0    0    -1  
$EndComp
Text Label 6000 2850 0    50   ~ 0
Row_4
Text Label 5600 2550 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K47
U 1 1 604C45AC
P 6600 2550
F 0 "K47" H 6600 2783 60  0000 C CNN
F 1 "KEYSW" H 6600 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6600 2550 60  0001 C CNN
F 3 "" H 6600 2550 60  0000 C CNN
	1    6600 2550
	1    0    0    -1  
$EndComp
Text Label 6800 2850 0    50   ~ 0
Row_4
Text Label 6400 2550 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K48
U 1 1 604C45AB
P 7400 2550
F 0 "K48" H 7400 2783 60  0000 C CNN
F 1 "KEYSW" H 7400 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7400 2550 60  0001 C CNN
F 3 "" H 7400 2550 60  0000 C CNN
	1    7400 2550
	1    0    0    -1  
$EndComp
Text Label 7600 2850 0    50   ~ 0
Row_5
Text Label 7200 2550 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K49
U 1 1 604C45A9
P 8200 2550
F 0 "K49" H 8200 2783 60  0000 C CNN
F 1 "KEYSW" H 8200 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8200 2550 60  0001 C CNN
F 3 "" H 8200 2550 60  0000 C CNN
	1    8200 2550
	1    0    0    -1  
$EndComp
Text Label 8400 2850 0    50   ~ 0
Row_5
Text Label 8000 2550 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K50
U 1 1 604C45A8
P 9000 2550
F 0 "K50" H 9000 2783 60  0000 C CNN
F 1 "KEYSW" H 9000 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9000 2550 60  0001 C CNN
F 3 "" H 9000 2550 60  0000 C CNN
	1    9000 2550
	1    0    0    -1  
$EndComp
Text Label 9200 2850 0    50   ~ 0
Row_5
Text Label 8800 2550 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K51
U 1 1 604C45A6
P 9800 2550
F 0 "K51" H 9800 2783 60  0000 C CNN
F 1 "KEYSW" H 9800 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9800 2550 60  0001 C CNN
F 3 "" H 9800 2550 60  0000 C CNN
	1    9800 2550
	1    0    0    -1  
$EndComp
Text Label 10000 2850 0    50   ~ 0
Row_5
Text Label 9600 2550 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K52
U 1 1 604C45A5
P 10600 2550
F 0 "K52" H 10600 2783 60  0000 C CNN
F 1 "KEYSW" H 10600 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10600 2550 60  0001 C CNN
F 3 "" H 10600 2550 60  0000 C CNN
	1    10600 2550
	1    0    0    -1  
$EndComp
Text Label 10800 2850 0    50   ~ 0
Row_4
Text Label 10400 2550 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K53
U 1 1 604C45A7
P 11900 2550
F 0 "K53" H 11900 2783 60  0000 C CNN
F 1 "KEYSW" H 11900 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_2.25u_PCB" H 11900 2550 60  0001 C CNN
F 3 "" H 11900 2550 60  0000 C CNN
	1    11900 2550
	1    0    0    -1  
$EndComp
Text Label 12100 2850 0    50   ~ 0
Row_3
Text Label 11700 2550 2    50   ~ 0
Col_2
$Comp
L Switch:SW_Push K54
U 1 1 604C45AA
P 13200 2550
F 0 "K54" H 13200 2783 60  0000 C CNN
F 1 "KEYSW" H 13200 2450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 13200 2550 60  0001 C CNN
F 3 "" H 13200 2550 60  0000 C CNN
	1    13200 2550
	1    0    0    -1  
$EndComp
Text Label 13400 2850 0    50   ~ 0
Row_0
Text Label 13000 2550 2    50   ~ 0
Col_4
$Comp
L Switch:SW_Push K55
U 1 1 604C45AD
P 1700 3050
F 0 "K55" H 1700 3283 60  0000 C CNN
F 1 "KEYSW" H 1700 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_2.25u_PCB" H 1700 3050 60  0001 C CNN
F 3 "" H 1700 3050 60  0000 C CNN
	1    1700 3050
	1    0    0    -1  
$EndComp
Text Label 1900 3350 0    50   ~ 0
Row_5
Text Label 1500 3050 2    50   ~ 0
Col_1
$Comp
L Switch:SW_Push K56
U 1 1 604C45B0
P 3000 3050
F 0 "K56" H 3000 3283 60  0000 C CNN
F 1 "KEYSW" H 3000 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3000 3050 60  0001 C CNN
F 3 "" H 3000 3050 60  0000 C CNN
	1    3000 3050
	1    0    0    -1  
$EndComp
Text Label 3200 3350 0    50   ~ 0
Row_3
Text Label 2800 3050 2    50   ~ 0
Col_15
$Comp
L Switch:SW_Push K57
U 1 1 604C45B3
P 3800 3050
F 0 "K57" H 3800 3283 60  0000 C CNN
F 1 "KEYSW" H 3800 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 3800 3050 60  0001 C CNN
F 3 "" H 3800 3050 60  0000 C CNN
	1    3800 3050
	1    0    0    -1  
$EndComp
Text Label 4000 3350 0    50   ~ 0
Row_3
Text Label 3600 3050 2    50   ~ 0
Col_14
$Comp
L Switch:SW_Push K58
U 1 1 604C45B6
P 4600 3050
F 0 "K58" H 4600 3283 60  0000 C CNN
F 1 "KEYSW" H 4600 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 4600 3050 60  0001 C CNN
F 3 "" H 4600 3050 60  0000 C CNN
	1    4600 3050
	1    0    0    -1  
$EndComp
Text Label 4800 3350 0    50   ~ 0
Row_3
Text Label 4400 3050 2    50   ~ 0
Col_13
$Comp
L Switch:SW_Push K59
U 1 1 604C45B9
P 5400 3050
F 0 "K59" H 5400 3283 60  0000 C CNN
F 1 "KEYSW" H 5400 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 5400 3050 60  0001 C CNN
F 3 "" H 5400 3050 60  0000 C CNN
	1    5400 3050
	1    0    0    -1  
$EndComp
Text Label 5600 3350 0    50   ~ 0
Row_3
Text Label 5200 3050 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K60
U 1 1 604C458F
P 6200 3050
F 0 "K60" H 6200 3283 60  0000 C CNN
F 1 "KEYSW" H 6200 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 6200 3050 60  0001 C CNN
F 3 "" H 6200 3050 60  0000 C CNN
	1    6200 3050
	1    0    0    -1  
$EndComp
Text Label 6400 3350 0    50   ~ 0
Row_2
Text Label 6000 3050 2    50   ~ 0
Col_12
$Comp
L Switch:SW_Push K61
U 1 1 604C4592
P 7000 3050
F 0 "K61" H 7000 3283 60  0000 C CNN
F 1 "KEYSW" H 7000 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7000 3050 60  0001 C CNN
F 3 "" H 7000 3050 60  0000 C CNN
	1    7000 3050
	1    0    0    -1  
$EndComp
Text Label 7200 3350 0    50   ~ 0
Row_2
Text Label 6800 3050 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K62
U 1 1 604C4595
P 7800 3050
F 0 "K62" H 7800 3283 60  0000 C CNN
F 1 "KEYSW" H 7800 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 7800 3050 60  0001 C CNN
F 3 "" H 7800 3050 60  0000 C CNN
	1    7800 3050
	1    0    0    -1  
$EndComp
Text Label 8000 3350 0    50   ~ 0
Row_3
Text Label 7600 3050 2    50   ~ 0
Col_11
$Comp
L Switch:SW_Push K63
U 1 1 604C4598
P 8600 3050
F 0 "K63" H 8600 3283 60  0000 C CNN
F 1 "KEYSW" H 8600 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 8600 3050 60  0001 C CNN
F 3 "" H 8600 3050 60  0000 C CNN
	1    8600 3050
	1    0    0    -1  
$EndComp
Text Label 8800 3350 0    50   ~ 0
Row_3
Text Label 8400 3050 2    50   ~ 0
Col_10
$Comp
L Switch:SW_Push K64
U 1 1 604C459B
P 9400 3050
F 0 "K64" H 9400 3283 60  0000 C CNN
F 1 "KEYSW" H 9400 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 9400 3050 60  0001 C CNN
F 3 "" H 9400 3050 60  0000 C CNN
	1    9400 3050
	1    0    0    -1  
$EndComp
Text Label 9600 3350 0    50   ~ 0
Row_3
Text Label 9200 3050 2    50   ~ 0
Col_9
$Comp
L Switch:SW_Push K65
U 1 1 604C459E
P 10200 3050
F 0 "K65" H 10200 3283 60  0000 C CNN
F 1 "KEYSW" H 10200 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 10200 3050 60  0001 C CNN
F 3 "" H 10200 3050 60  0000 C CNN
	1    10200 3050
	1    0    0    -1  
$EndComp
Text Label 10400 3350 0    50   ~ 0
Row_2
Text Label 10000 3050 2    50   ~ 0
Col_3
$Comp
L Switch:SW_Push K66
U 1 1 604C45A0
P 11300 3050
F 0 "K66" H 11300 3283 60  0000 C CNN
F 1 "KEYSW" H 11300 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.75u_PCB" H 11300 3050 60  0001 C CNN
F 3 "" H 11300 3050 60  0000 C CNN
	1    11300 3050
	1    0    0    -1  
$EndComp
Text Label 11500 3350 0    50   ~ 0
Row_6
Text Label 11100 3050 2    50   ~ 0
Col_1
$Comp
L Switch:SW_Push K67
U 1 1 604C45A3
P 12400 3050
F 0 "K67" H 12400 3283 60  0000 C CNN
F 1 "KEYSW" H 12400 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 12400 3050 60  0001 C CNN
F 3 "" H 12400 3050 60  0000 C CNN
	1    12400 3050
	1    0    0    -1  
$EndComp
Text Label 12600 3350 0    50   ~ 0
Row_4
Text Label 12200 3050 2    50   ~ 0
Col_8
$Comp
L Switch:SW_Push K68
U 1 1 604C45D0
P 13200 3050
F 0 "K68" H 13200 3283 60  0000 C CNN
F 1 "KEYSW" H 13200 2950 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 13200 3050 60  0001 C CNN
F 3 "" H 13200 3050 60  0000 C CNN
	1    13200 3050
	1    0    0    -1  
$EndComp
Text Label 13400 3350 0    50   ~ 0
Row_5
Text Label 13000 3050 2    50   ~ 0
Col_4
$Comp
L Switch:SW_Push K69
U 1 1 604C45D4
P 1300 3550
F 0 "K69" H 1300 3783 60  0000 C CNN
F 1 "KEYSW" H 1300 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.25u_PCB" H 1300 3550 60  0001 C CNN
F 3 "" H 1300 3550 60  0000 C CNN
	1    1300 3550
	1    0    0    -1  
$EndComp
Text Label 1500 3850 0    50   ~ 0
Row_1
Text Label 1100 3550 2    50   ~ 0
Col_5
$Comp
L Switch:SW_Push K70
U 1 1 604C45D8
P 2200 3550
F 0 "K70" H 2200 3783 60  0000 C CNN
F 1 "KEYSW" H 2200 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 2200 3550 60  0001 C CNN
F 3 "" H 2200 3550 60  0000 C CNN
	1    2200 3550
	1    0    0    -1  
$EndComp
Text Label 2400 3850 0    50   ~ 0
Row_6
Text Label 2000 3550 2    50   ~ 0
Col_6
$Comp
L Switch:SW_Push K71
U 1 1 604C45C4
P 3100 3550
F 0 "K71" H 3100 3783 60  0000 C CNN
F 1 "KEYSW" H 3100 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.25u_PCB" H 3100 3550 60  0001 C CNN
F 3 "" H 3100 3550 60  0000 C CNN
	1    3100 3550
	1    0    0    -1  
$EndComp
Text Label 3300 3850 0    50   ~ 0
Row_4
Text Label 2900 3550 2    50   ~ 0
Col_4
$Comp
L Switch:SW_Push K72
U 1 1 604C45C1
P 6400 3550
F 0 "K72" H 6400 3783 60  0000 C CNN
F 1 "KEYSW" H 6400 3450 60  0001 C CNN
F 2 "7u-space:SW_Cherry_MX_7u_PCB" H 6400 3550 60  0001 C CNN
F 3 "" H 6400 3550 60  0000 C CNN
	1    6400 3550
	1    0    0    -1  
$EndComp
Text Label 6600 3850 0    50   ~ 0
Row_4
Text Label 6200 3550 2    50   ~ 0
Col_0
$Comp
L Switch:SW_Push K73
U 1 1 604C45C5
P 9700 3550
F 0 "K73" H 9700 3783 60  0000 C CNN
F 1 "KEYSW" H 9700 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.25u_PCB" H 9700 3550 60  0001 C CNN
F 3 "" H 9700 3550 60  0000 C CNN
	1    9700 3550
	1    0    0    -1  
$EndComp
Text Label 9900 3850 0    50   ~ 0
Row_2
Text Label 9500 3550 2    50   ~ 0
Col_4
$Comp
L Switch:SW_Push K74
U 1 1 604C45C9
P 10700 3550
F 0 "K74" H 10700 3783 60  0000 C CNN
F 1 "KEYSW" H 10700 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.25u_PCB" H 10700 3550 60  0001 C CNN
F 3 "" H 10700 3550 60  0000 C CNN
	1    10700 3550
	1    0    0    -1  
$EndComp
Text Label 10900 3850 0    50   ~ 0
Row_3
Text Label 10500 3550 2    50   ~ 0
Col_5
$Comp
L Switch:SW_Push K75
U 1 1 604C45CA
P 11600 3550
F 0 "K75" H 11600 3783 60  0000 C CNN
F 1 "KEYSW" H 11600 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 11600 3550 60  0001 C CNN
F 3 "" H 11600 3550 60  0000 C CNN
	1    11600 3550
	1    0    0    -1  
$EndComp
Text Label 11800 3850 0    50   ~ 0
Row_2
Text Label 11400 3550 2    50   ~ 0
Col_8
$Comp
L Switch:SW_Push K76
U 1 1 604C45BE
P 12400 3550
F 0 "K76" H 12400 3783 60  0000 C CNN
F 1 "KEYSW" H 12400 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 12400 3550 60  0001 C CNN
F 3 "" H 12400 3550 60  0000 C CNN
	1    12400 3550
	1    0    0    -1  
$EndComp
Text Label 12600 3850 0    50   ~ 0
Row_2
Text Label 12200 3550 2    50   ~ 0
Col_0
$Comp
L Switch:SW_Push K77
U 1 1 604C45D5
P 13200 3550
F 0 "K77" H 13200 3783 60  0000 C CNN
F 1 "KEYSW" H 13200 3450 60  0001 C CNN
F 2 "Button_Switch_Keyboard:SW_Cherry_MX_1.00u_PCB" H 13200 3550 60  0001 C CNN
F 3 "" H 13200 3550 60  0000 C CNN
	1    13200 3550
	1    0    0    -1  
$EndComp
Text Label 13400 3850 0    50   ~ 0
Row_2
Text Label 13000 3550 2    50   ~ 0
Col_7
$Comp
L Mechanical:MountingHole H2
U 1 1 5E99AD30
P 1200 9150
F 0 "H2" H 1300 9196 50  0000 L CNN
F 1 "MountingHole" H 1300 9105 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 9150 50  0001 C CNN
F 3 "~" H 1200 9150 50  0001 C CNN
	1    1200 9150
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H1
U 1 1 5E99B06F
P 1200 8700
F 0 "H1" H 1300 8746 50  0000 L CNN
F 1 "MountingHole" H 1300 8655 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 8700 50  0001 C CNN
F 3 "~" H 1200 8700 50  0001 C CNN
	1    1200 8700
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H4
U 1 1 5E99CF54
P 2050 8700
F 0 "H4" H 2150 8746 50  0000 L CNN
F 1 "MountingHole" H 2150 8655 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 8700 50  0001 C CNN
F 3 "~" H 2050 8700 50  0001 C CNN
	1    2050 8700
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H3
U 1 1 5E99E1A5
P 2050 9150
F 0 "H3" H 2150 9196 50  0000 L CNN
F 1 "MountingHole" H 2150 9105 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 9150 50  0001 C CNN
F 3 "~" H 2050 9150 50  0001 C CNN
	1    2050 9150
	1    0    0    -1  
$EndComp
Text Notes 950  1200 0    50   ~ 0
Esc
Text Notes 2150 1200 0    50   ~ 0
F1/F11
Text Notes 2950 1200 0    50   ~ 0
F2/F12
Text Notes 3750 1200 0    50   ~ 0
F3
Text Notes 4550 1200 0    50   ~ 0
F4
Text Notes 5750 1200 0    50   ~ 0
F5
Text Notes 6550 1200 0    50   ~ 0
F6
Text Notes 7350 1200 0    50   ~ 0
F7
Text Notes 8150 1200 0    50   ~ 0
F8
Text Notes 9350 1200 0    50   ~ 0
F9
Text Notes 10150 1200 0    50   ~ 0
F10
Text Notes 950  1700 0    50   ~ 0
~
Text Notes 950  1700 0    50   ~ 0
`
Text Notes 1750 1700 0    50   ~ 0
1
Text Notes 2550 1700 0    50   ~ 0
2
Text Notes 3350 1700 0    50   ~ 0
3
Text Notes 4150 1700 0    50   ~ 0
4
Text Notes 4950 1700 0    50   ~ 0
5
Text Notes 5750 1700 0    50   ~ 0
6
Text Notes 6550 1700 0    50   ~ 0
7
Text Notes 7350 1700 0    50   ~ 0
8
Text Notes 8150 1700 0    50   ~ 0
9
Text Notes 8950 1700 0    50   ~ 0
0
Text Notes 9750 1700 0    50   ~ 0
-
Text Notes 10550 1700 0    50   ~ 0
=
Text Notes 11750 1700 0    50   ~ 0
Bksp
Text Notes 12950 1700 0    50   ~ 0
NumLk
Text Notes 1150 2200 0    50   ~ 0
Tab
Text Notes 2150 2200 0    50   ~ 0
Q
Text Notes 2950 2200 0    50   ~ 0
W
Text Notes 3750 2200 0    50   ~ 0
E
Text Notes 4550 2200 0    50   ~ 0
R
Text Notes 5350 2200 0    50   ~ 0
T
Text Notes 6150 2200 0    50   ~ 0
Y
Text Notes 6950 2200 0    50   ~ 0
U
Text Notes 7750 2200 0    50   ~ 0
I
Text Notes 8550 2200 0    50   ~ 0
O
Text Notes 9350 2200 0    50   ~ 0
P
Text Notes 10150 2200 0    50   ~ 0
[
Text Notes 10950 2200 0    50   ~ 0
]
Text Notes 11950 2200 0    50   ~ 0
\
Text Notes 12950 2200 0    50   ~ 0
Del
Text Notes 1250 2700 0    50   ~ 0
CapsLk
Text Notes 2350 2700 0    50   ~ 0
A
Text Notes 3150 2700 0    50   ~ 0
S
Text Notes 3950 2700 0    50   ~ 0
D
Text Notes 4750 2700 0    50   ~ 0
F
Text Notes 5550 2700 0    50   ~ 0
G
Text Notes 6350 2700 0    50   ~ 0
H
Text Notes 7150 2700 0    50   ~ 0
J
Text Notes 7950 2700 0    50   ~ 0
K
Text Notes 8750 2700 0    50   ~ 0
L
Text Notes 9550 2700 0    50   ~ 0
;
Text Notes 10350 2700 0    50   ~ 0
'
Text Notes 11650 2700 0    50   ~ 0
Enter
Text Notes 12950 2700 0    50   ~ 0
PrtSc
Text Notes 1450 3200 0    50   ~ 0
Shift
Text Notes 2750 3200 0    50   ~ 0
Z
Text Notes 3550 3200 0    50   ~ 0
X
Text Notes 4350 3200 0    50   ~ 0
C
Text Notes 5150 3200 0    50   ~ 0
V
Text Notes 5950 3200 0    50   ~ 0
B
Text Notes 6750 3200 0    50   ~ 0
N
Text Notes 7550 3200 0    50   ~ 0
M
Text Notes 8350 3200 0    50   ~ 0
,
Text Notes 9150 3200 0    50   ~ 0
.
Text Notes 9950 3200 0    50   ~ 0
/
Text Notes 11050 3200 0    50   ~ 0
Shift
Text Notes 12150 3200 0    50   ~ 0
Up
Text Notes 12950 3200 0    50   ~ 0
Fn
Text Notes 1050 3700 0    50   ~ 0
Ctrl
Text Notes 1950 3700 0    50   ~ 0
Rpi
Text Notes 2850 3700 0    50   ~ 0
Alt
Text Notes 6150 3700 0    50   ~ 0
Space
Text Notes 9450 3700 0    50   ~ 0
Alt
Text Notes 10450 3700 0    50   ~ 0
Ctrl
Text Notes 11350 3700 0    50   ~ 0
Left
Text Notes 12150 3700 0    50   ~ 0
Down
Text Notes 12950 3700 0    50   ~ 0
Right
Text Label 13000 1550 2    50   ~ 0
Col_0
Text Label 9000 1550 2    50   ~ 0
Col_3
$Comp
L Connector_Generic:Conn_01x26 J1
U 1 1 605EF52D
P 10700 6200
F 0 "J1" H 10780 6192 50  0000 L CNN
F 1 "Conn_01x26" H 10780 6101 50  0000 L CNN
F 2 "Connector_FFC-FPC:TE_2-84952-6_1x26-1MP_P1.0mm_Horizontal" H 10700 6200 50  0001 C CNN
F 3 "~" H 10700 6200 50  0001 C CNN
	1    10700 6200
	1    0    0    -1  
$EndComp
Text Label 10100 5000 0    50   ~ 0
Row_7
Text Label 10100 5100 0    50   ~ 0
Row_6
Text Label 10100 5200 0    50   ~ 0
Row_5
Text Label 10100 5300 0    50   ~ 0
Row_4
Text Label 10100 5400 0    50   ~ 0
Row_3
Text Label 10100 5500 0    50   ~ 0
Row_2
Text Label 10100 5600 0    50   ~ 0
Row_1
Text Label 10100 5700 0    50   ~ 0
Row_0
Wire Wire Line
	10100 5700 10500 5700
Wire Wire Line
	10500 5600 10100 5600
Wire Wire Line
	10100 5500 10500 5500
Wire Wire Line
	10500 5400 10100 5400
Wire Wire Line
	10100 5300 10500 5300
Wire Wire Line
	10500 5200 10100 5200
Wire Wire Line
	10100 5100 10500 5100
Wire Wire Line
	10500 5000 10100 5000
Text Label 10100 5800 0    50   ~ 0
Col_15
Text Label 10100 5900 0    50   ~ 0
Col_14
Text Label 10100 6000 0    50   ~ 0
Col_13
Text Label 10100 6100 0    50   ~ 0
Col_12
Text Label 10100 6200 0    50   ~ 0
Col_11
Text Label 10100 6300 0    50   ~ 0
Col_10
Text Label 10100 6400 0    50   ~ 0
Col_9
Text Label 10100 6500 0    50   ~ 0
Col_8
Text Label 10100 6700 0    50   ~ 0
Col_7
Text Label 10100 6900 0    50   ~ 0
Col_6
Text Label 10100 7000 0    50   ~ 0
Col_5
Text Label 10100 7500 0    50   ~ 0
Col_0
Text Label 10100 7400 0    50   ~ 0
Col_1
Text Label 10100 7300 0    50   ~ 0
Col_2
Text Label 10100 7200 0    50   ~ 0
Col_3
Text Label 10100 7100 0    50   ~ 0
Col_4
Wire Wire Line
	10100 5800 10500 5800
Wire Wire Line
	10500 5900 10100 5900
Wire Wire Line
	10100 6000 10500 6000
Wire Wire Line
	10500 6100 10100 6100
Wire Wire Line
	10500 6200 10100 6200
Wire Wire Line
	10100 6300 10500 6300
Wire Wire Line
	10500 6400 10100 6400
Wire Wire Line
	10100 6500 10500 6500
Wire Wire Line
	10500 6700 10100 6700
Wire Wire Line
	10100 6900 10500 6900
Wire Wire Line
	10500 7000 10100 7000
Wire Wire Line
	10100 7100 10500 7100
Wire Wire Line
	10500 7200 10100 7200
Wire Wire Line
	10100 7300 10500 7300
Wire Wire Line
	10500 7400 10100 7400
Wire Wire Line
	10100 7500 10500 7500
$Comp
L suf_led_display:S60401AS DS1
U 1 1 606B9950
P 6850 8100
F 0 "DS1" H 7780 8146 50  0000 L CNN
F 1 "S60401AS" H 7780 8055 50  0000 L CNN
F 2 "14seg:S60401AS" H 7650 7800 50  0001 L BNN
F 3 "" H 7875 7700 50  0001 L BNN
F 4 "DISPLAY RED 6DIG 14SEG CC 0.4\" TH" H 7650 7700 50  0001 L BNN "Description"
	1    6850 8100
	1    0    0    -1  
$EndComp
$Comp
L holtek:HT16K33 U1
U 1 1 606D2FBA
P 5350 6150
F 0 "U1" H 5350 7653 60  0000 C CNN
F 1 "HT16K33" H 5350 7547 60  0000 C CNN
F 2 "Package_SO:SOIC-28W_7.5x18.7mm_P1.27mm" H 5350 7441 60  0000 C CNN
F 3 "" H 5350 7300 60  0000 C CNN
	1    5350 6150
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x04 J2
U 1 1 606F2829
P 2800 6000
F 0 "J2" H 2718 6317 50  0000 C CNN
F 1 "Conn_01x04" H 2718 6226 50  0000 C CNN
F 2 "Connector_JST:JST_PH_S4B-PH-SM4-TB_1x04-1MP_P2.00mm_Horizontal" H 2800 6000 50  0001 C CNN
F 3 "~" H 2800 6000 50  0001 C CNN
	1    2800 6000
	-1   0    0    -1  
$EndComp
Wire Wire Line
	3000 5900 4000 5900
Wire Wire Line
	4500 5900 4500 7400
Wire Wire Line
	4500 7400 4700 7400
Wire Wire Line
	3000 6000 3100 6000
Wire Wire Line
	3100 6000 3100 5000
Wire Wire Line
	3100 5000 4000 5000
Wire Wire Line
	3000 6100 3200 6100
Wire Wire Line
	3200 6100 3200 5300
Wire Wire Line
	3200 5300 4700 5300
Wire Wire Line
	4700 5200 3300 5200
Wire Wire Line
	3300 5200 3300 6200
Wire Wire Line
	3300 6200 3000 6200
Wire Wire Line
	6000 7000 6750 7000
Wire Wire Line
	6000 7100 6550 7100
Wire Wire Line
	6000 7200 6350 7200
Wire Wire Line
	6350 7700 6350 7200
Wire Wire Line
	6550 7100 6550 7700
Wire Wire Line
	6750 7700 6750 7000
Wire Wire Line
	6000 6900 6950 6900
Wire Wire Line
	6950 6900 6950 7700
Wire Wire Line
	7150 7700 7150 6800
Wire Wire Line
	6000 6800 7150 6800
Wire Wire Line
	7350 6700 7350 7700
Wire Wire Line
	6000 6700 7350 6700
Wire Wire Line
	8050 8600 7150 8600
Wire Wire Line
	7150 8500 7150 8600
Wire Wire Line
	6000 6500 8050 6500
Wire Wire Line
	8050 6500 8050 8600
Wire Wire Line
	6000 6400 8100 6400
Wire Wire Line
	8100 6400 8100 8650
Wire Wire Line
	6250 8500 6250 8650
Wire Wire Line
	6250 8650 8100 8650
Wire Wire Line
	6150 8500 6150 8700
Wire Wire Line
	6150 8700 8150 8700
Wire Wire Line
	8150 8700 8150 6300
Wire Wire Line
	8150 6300 6000 6300
Wire Wire Line
	6650 8500 6650 8750
Wire Wire Line
	6650 8750 8200 8750
Wire Wire Line
	8200 8750 8200 6200
Wire Wire Line
	8200 6200 6000 6200
Wire Wire Line
	7050 8500 7050 8800
Wire Wire Line
	7050 8800 8250 8800
Wire Wire Line
	8250 8800 8250 6100
Wire Wire Line
	8250 6100 6000 6100
Wire Wire Line
	6950 8500 6950 8850
Wire Wire Line
	6950 8850 8300 8850
Wire Wire Line
	8300 8850 8300 6000
Wire Wire Line
	8300 6000 6000 6000
Wire Wire Line
	6000 5900 8350 5900
Wire Wire Line
	8350 5900 8350 8900
Wire Wire Line
	8350 8900 6350 8900
Wire Wire Line
	6350 8900 6350 8500
Wire Wire Line
	6450 8500 6450 8950
Wire Wire Line
	6450 8950 8400 8950
Wire Wire Line
	8400 8950 8400 5800
Wire Wire Line
	8400 5800 6000 5800
Wire Wire Line
	8450 9000 8450 5700
Wire Wire Line
	8450 5700 6000 5700
Wire Wire Line
	8500 9050 8500 5600
Wire Wire Line
	8500 5600 6000 5600
Wire Wire Line
	7450 8500 7450 9100
Wire Wire Line
	7450 9100 8550 9100
Wire Wire Line
	8550 9100 8550 5500
Wire Wire Line
	8550 5500 6000 5500
Wire Wire Line
	7350 8500 7350 9150
Wire Wire Line
	7350 9150 8600 9150
Wire Wire Line
	8600 9150 8600 5400
Wire Wire Line
	8600 5400 6000 5400
Wire Wire Line
	7250 8500 7250 9200
Wire Wire Line
	7250 9200 8650 9200
Wire Wire Line
	8650 9200 8650 5300
Wire Wire Line
	8650 5300 6000 5300
Wire Wire Line
	6850 8500 6850 9250
Wire Wire Line
	6850 9250 8700 9250
Wire Wire Line
	8700 9250 8700 5200
Wire Wire Line
	8700 5200 6000 5200
Wire Wire Line
	6750 8500 6750 9300
Wire Wire Line
	6750 9300 8750 9300
Wire Wire Line
	8750 9300 8750 5100
Wire Wire Line
	8750 5100 6000 5100
Wire Wire Line
	7550 8500 7550 9000
Wire Wire Line
	7550 9000 8450 9000
Wire Wire Line
	6550 8500 6550 9050
Wire Wire Line
	6550 9050 8500 9050
$Comp
L power:GND #PWR0101
U 1 1 607B4E9C
P 4500 7500
F 0 "#PWR0101" H 4500 7250 50  0001 C CNN
F 1 "GND" H 4505 7327 50  0000 C CNN
F 2 "" H 4500 7500 50  0001 C CNN
F 3 "" H 4500 7500 50  0001 C CNN
	1    4500 7500
	1    0    0    -1  
$EndComp
Wire Wire Line
	4500 7400 4500 7500
Connection ~ 4500 7400
Text Label 3500 5200 0    50   ~ 0
SCL
Text Label 3500 5300 0    50   ~ 0
SDA
$Comp
L Device:C C1
U 1 1 607BD6AB
P 4000 5600
F 0 "C1" H 4115 5646 50  0000 L CNN
F 1 "10u" H 4115 5555 50  0000 L CNN
F 2 "Capacitor_SMD:C_0805_2012Metric" H 4038 5450 50  0001 C CNN
F 3 "~" H 4000 5600 50  0001 C CNN
F 4 "C15850" H 4000 5600 50  0001 C CNN "LCSC"
	1    4000 5600
	1    0    0    -1  
$EndComp
Wire Wire Line
	4000 5750 4000 5900
Connection ~ 4000 5900
Wire Wire Line
	4000 5900 4500 5900
Wire Wire Line
	4000 5450 4000 5000
Connection ~ 4000 5000
Wire Wire Line
	4000 5000 4700 5000
$Comp
L Device:D D78
U 1 1 607D23E2
P 7700 6700
F 0 "D78" V 7800 6700 60  0000 R CNN
F 1 "D" V 7450 6650 60  0001 R CNN
F 2 "Diode_SMD:D_SOD-123F" H 7300 6700 60  0001 C CNN
F 3 "" H 7300 6700 60  0000 C CNN
F 4 "C64898" H 7700 6700 50  0001 C CNN "LCSC"
	1    7700 6700
	-1   0    0    1   
$EndComp
Wire Wire Line
	7350 6700 7550 6700
Connection ~ 7350 6700
$Comp
L Device:R R1
U 1 1 607D8896
P 8900 6450
F 0 "R1" H 8970 6496 50  0000 L CNN
F 1 "39K" H 8970 6405 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 8830 6450 50  0001 C CNN
F 3 "~" H 8900 6450 50  0001 C CNN
F 4 "C23153" H 8900 6450 50  0001 C CNN "LCSC"
	1    8900 6450
	1    0    0    -1  
$EndComp
$Comp
L Device:R R2
U 1 1 607D9F7F
P 9200 6450
F 0 "R2" H 9270 6496 50  0000 L CNN
F 1 "39K" H 9270 6405 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 9130 6450 50  0001 C CNN
F 3 "~" H 9200 6450 50  0001 C CNN
F 4 "C23153" H 9200 6450 50  0001 C CNN "LCSC"
	1    9200 6450
	1    0    0    -1  
$EndComp
$Comp
L Device:R R3
U 1 1 607DA284
P 9500 6450
F 0 "R3" H 9570 6496 50  0000 L CNN
F 1 "39K" H 9570 6405 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 9430 6450 50  0001 C CNN
F 3 "~" H 9500 6450 50  0001 C CNN
F 4 "C23153" H 9500 6450 50  0001 C CNN "LCSC"
	1    9500 6450
	1    0    0    -1  
$EndComp
$Comp
L Jumper:SolderJumper_2_Open JP1
U 1 1 607DA874
P 8900 6050
F 0 "JP1" V 8854 6118 50  0000 L CNN
F 1 "SolderJumper_2_Open" V 8945 6118 50  0000 L CNN
F 2 "Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm" H 8900 6050 50  0001 C CNN
F 3 "~" H 8900 6050 50  0001 C CNN
	1    8900 6050
	0    1    1    0   
$EndComp
$Comp
L Jumper:SolderJumper_2_Open JP2
U 1 1 607DBF89
P 9200 6050
F 0 "JP2" V 9154 6118 50  0000 L CNN
F 1 "SolderJumper_2_Open" V 9245 6118 50  0000 L CNN
F 2 "Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm" H 9200 6050 50  0001 C CNN
F 3 "~" H 9200 6050 50  0001 C CNN
	1    9200 6050
	0    1    1    0   
$EndComp
$Comp
L Jumper:SolderJumper_2_Open JP3
U 1 1 607DC289
P 9500 6050
F 0 "JP3" V 9454 6118 50  0000 L CNN
F 1 "SolderJumper_2_Open" V 9545 6118 50  0000 L CNN
F 2 "Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm" H 9500 6050 50  0001 C CNN
F 3 "~" H 9500 6050 50  0001 C CNN
	1    9500 6050
	0    1    1    0   
$EndComp
Wire Wire Line
	7850 6700 8900 6700
Wire Wire Line
	8900 6700 8900 6600
Wire Wire Line
	8900 6700 9200 6700
Wire Wire Line
	9200 6700 9200 6600
Connection ~ 8900 6700
Wire Wire Line
	9200 6700 9500 6700
Wire Wire Line
	9500 6700 9500 6600
Connection ~ 9200 6700
Wire Wire Line
	8900 6300 8900 6200
Wire Wire Line
	9200 6200 9200 6300
Wire Wire Line
	9500 6300 9500 6200
Wire Wire Line
	8700 5200 8900 5200
Wire Wire Line
	8900 5200 8900 5900
Connection ~ 8700 5200
Wire Wire Line
	8750 5100 9200 5100
Wire Wire Line
	9200 5100 9200 5900
Connection ~ 8750 5100
Wire Wire Line
	6000 5000 9500 5000
Wire Wire Line
	9500 5000 9500 5900
$Comp
L Mechanical:MountingHole H6
U 1 1 6084996B
P 1200 10100
F 0 "H6" H 1300 10146 50  0000 L CNN
F 1 "MountingHole" H 1300 10055 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 10100 50  0001 C CNN
F 3 "~" H 1200 10100 50  0001 C CNN
	1    1200 10100
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H5
U 1 1 60849975
P 1200 9650
F 0 "H5" H 1300 9696 50  0000 L CNN
F 1 "MountingHole" H 1300 9605 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 9650 50  0001 C CNN
F 3 "~" H 1200 9650 50  0001 C CNN
	1    1200 9650
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H7
U 1 1 6084997F
P 2050 9650
F 0 "H7" H 2150 9696 50  0000 L CNN
F 1 "MountingHole" H 2150 9605 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 9650 50  0001 C CNN
F 3 "~" H 2050 9650 50  0001 C CNN
	1    2050 9650
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H8
U 1 1 60849989
P 2050 10100
F 0 "H8" H 2150 10146 50  0000 L CNN
F 1 "MountingHole" H 2150 10055 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 10100 50  0001 C CNN
F 3 "~" H 2050 10100 50  0001 C CNN
	1    2050 10100
	1    0    0    -1  
$EndComp
Wire Wire Line
	2600 1050 2600 1350
Wire Wire Line
	3000 1550 3000 1850
Wire Wire Line
	2600 2050 2600 2350
Wire Wire Line
	2200 1550 2200 1850
Wire Wire Line
	1400 1850 1400 1550
Wire Wire Line
	1600 2050 1600 2350
Wire Wire Line
	1400 1350 1400 1050
Wire Wire Line
	6600 2350 6600 2050
Wire Wire Line
	6200 1350 6200 1050
Wire Wire Line
	5000 1050 5000 1350
Wire Wire Line
	5400 1550 5400 1850
Wire Wire Line
	5800 2050 5800 2350
Wire Wire Line
	5050 2350 5000 2350
Wire Wire Line
	5000 2350 5000 2050
Wire Wire Line
	4600 1850 4600 1550
Wire Wire Line
	4200 1350 4200 1050
Wire Wire Line
	3400 1350 3400 1050
Wire Wire Line
	3800 1550 3800 1850
Wire Wire Line
	4200 2050 4200 2350
Wire Wire Line
	3400 2350 3400 2050
Wire Wire Line
	7400 2350 7400 2050
Wire Wire Line
	8200 2050 8200 2350
Wire Wire Line
	9000 2050 9000 2350
Wire Wire Line
	9800 2350 9800 2050
Wire Wire Line
	10200 1850 10200 1550
Wire Wire Line
	7000 1050 7000 1350
Wire Wire Line
	7000 1550 7000 1850
Wire Wire Line
	7800 1550 7800 1850
Wire Wire Line
	9800 1050 9800 1350
Wire Wire Line
	9400 1550 9400 1850
Wire Wire Line
	8600 1850 8600 1550
Wire Wire Line
	8600 1350 8600 1050
Wire Wire Line
	7800 1350 7800 1050
Wire Wire Line
	10600 1050 10600 1350
Wire Wire Line
	10600 2050 10600 2350
Wire Wire Line
	11400 2050 11400 2350
Wire Wire Line
	11000 1550 11000 1850
Wire Wire Line
	12200 1550 12200 1850
Wire Wire Line
	12400 2050 12400 2350
Wire Wire Line
	13400 2050 13400 2350
Wire Wire Line
	13400 1550 13400 1850
Wire Wire Line
	9200 2550 9200 2850
Wire Wire Line
	8800 3050 8800 3350
Wire Wire Line
	9600 3050 9600 3350
Wire Wire Line
	9900 3550 9900 3850
Wire Wire Line
	10000 2550 10000 2850
Wire Wire Line
	10800 2550 10800 2850
Wire Wire Line
	10400 3050 10400 3350
Wire Wire Line
	10900 3850 10900 3550
Wire Wire Line
	11800 3850 11800 3550
Wire Wire Line
	12600 3050 12600 3350
Wire Wire Line
	12600 3550 12600 3850
Wire Wire Line
	13400 3550 13400 3850
Wire Wire Line
	13400 3050 13400 3350
Wire Wire Line
	13400 2550 13400 2850
Wire Wire Line
	12100 2550 12100 2850
Wire Wire Line
	11500 3050 11500 3350
Wire Wire Line
	1500 3550 1500 3850
Wire Wire Line
	2400 3550 2400 3850
Wire Wire Line
	3300 3550 3300 3850
Wire Wire Line
	6600 3550 6600 3850
Wire Wire Line
	8400 2550 8400 2850
Wire Wire Line
	8000 3050 8000 3350
Wire Wire Line
	7600 2550 7600 2850
Wire Wire Line
	7200 3050 7200 3350
Wire Wire Line
	6800 2550 6800 2850
Wire Wire Line
	6000 2550 6000 2850
Wire Wire Line
	6400 3050 6400 3350
Wire Wire Line
	5600 3350 5600 3050
Wire Wire Line
	5200 2850 5200 2550
Wire Wire Line
	4800 3350 4800 3050
Wire Wire Line
	4000 3350 4000 3050
Wire Wire Line
	4400 2850 4400 2550
Wire Wire Line
	3600 2850 3600 2550
Wire Wire Line
	3200 3350 3200 3050
Wire Wire Line
	2800 2850 2800 2550
Wire Wire Line
	1900 3350 1900 3050
Wire Wire Line
	1700 2850 1700 2550
Wire Wire Line
	6200 1550 6200 1850
$EndSCHEMATC
