EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr A3 16535 11693
encoding utf-8
Sheet 1 1
Title ""
Date "2021-03-12 22:09"
Rev ""
Comp ""
Comment1 "Author: "
Comment2 "Generated by klepcbgen.py v0.1"
Comment3 ""
Comment4 ""
$EndDescr
$Comp
L Mechanical:MountingHole H2
U 1 1 5E99AD30
P 1200 9150
F 0 "H2" H 1300 9196 50  0000 L CNN
F 1 "MountingHole" H 1300 9105 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 9150 50  0001 C CNN
F 3 "~" H 1200 9150 50  0001 C CNN
	1    1200 9150
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H1
U 1 1 5E99B06F
P 1200 8700
F 0 "H1" H 1300 8746 50  0000 L CNN
F 1 "MountingHole" H 1300 8655 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 1200 8700 50  0001 C CNN
F 3 "~" H 1200 8700 50  0001 C CNN
	1    1200 8700
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H4
U 1 1 5E99CF54
P 2050 8700
F 0 "H4" H 2150 8746 50  0000 L CNN
F 1 "MountingHole" H 2150 8655 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 8700 50  0001 C CNN
F 3 "~" H 2050 8700 50  0001 C CNN
	1    2050 8700
	1    0    0    -1  
$EndComp
$Comp
L Mechanical:MountingHole H3
U 1 1 5E99E1A5
P 2050 9150
F 0 "H3" H 2150 9196 50  0000 L CNN
F 1 "MountingHole" H 2150 9105 50  0000 L CNN
F 2 "MountingHole:MountingHole_3.2mm_M3_DIN965" H 2050 9150 50  0001 C CNN
F 3 "~" H 2050 9150 50  0001 C CNN
	1    2050 9150
	1    0    0    -1  
$EndComp
$Comp
L Connector_Generic:Conn_01x26 J1
U 1 1 605EF52D
P 10700 6200
F 0 "J1" H 10780 6192 50  0000 L CNN
F 1 "Conn_01x26" H 10780 6101 50  0000 L CNN
F 2 "Connector_FFC-FPC:TE_2-84952-6_1x26-1MP_P1.0mm_Horizontal" H 10700 6200 50  0001 C CNN
F 3 "~" H 10700 6200 50  0001 C CNN
	1    10700 6200
	1    0    0    -1  
$EndComp
Text Label 10100 5000 0    50   ~ 0
Row_7
Text Label 10100 5100 0    50   ~ 0
Row_6
Text Label 10100 5200 0    50   ~ 0
Row_5
Text Label 10100 5300 0    50   ~ 0
Row_4
Text Label 10100 5400 0    50   ~ 0
Row_3
Text Label 10100 5500 0    50   ~ 0
Row_2
Text Label 10100 5600 0    50   ~ 0
Row_1
Text Label 10100 5700 0    50   ~ 0
Row_0
Wire Wire Line
	10100 5700 10500 5700
Wire Wire Line
	10500 5600 10100 5600
Wire Wire Line
	10100 5500 10500 5500
Wire Wire Line
	10500 5400 10100 5400
Wire Wire Line
	10100 5300 10500 5300
Wire Wire Line
	10500 5200 10100 5200
Wire Wire Line
	10100 5100 10500 5100
Wire Wire Line
	10500 5000 10100 5000
Text Label 10100 5800 0    50   ~ 0
Col_15
Text Label 10100 5900 0    50   ~ 0
Col_14
Text Label 10100 6000 0    50   ~ 0
Col_13
Text Label 10100 6100 0    50   ~ 0
Col_12
Text Label 10100 6200 0    50   ~ 0
Col_11
Text Label 10100 6300 0    50   ~ 0
Col_10
Text Label 10100 6400 0    50   ~ 0
Col_9
Text Label 10100 6500 0    50   ~ 0
Col_8
Text Label 10100 6700 0    50   ~ 0
Col_7
Text Label 10100 6900 0    50   ~ 0
Col_6
Text Label 10100 7000 0    50   ~ 0
Col_5
Text Label 10100 7500 0    50   ~ 0
Col_0
Text Label 10100 7400 0    50   ~ 0
Col_1
Text Label 10100 7300 0    50   ~ 0
Col_2
Text Label 10100 7200 0    50   ~ 0
Col_3
Text Label 10100 7100 0    50   ~ 0
Col_4
Wire Wire Line
	10100 5800 10500 5800
Wire Wire Line
	10500 5900 10100 5900
Wire Wire Line
	10100 6000 10500 6000
Wire Wire Line
	10500 6100 10100 6100
Wire Wire Line
	10500 6200 10100 6200
Wire Wire Line
	10100 6300 10500 6300
Wire Wire Line
	10500 6400 10100 6400
Wire Wire Line
	10100 6500 10500 6500
Wire Wire Line
	10500 6700 10100 6700
Wire Wire Line
	10100 6900 10500 6900
Wire Wire Line
	10500 7000 10100 7000
Wire Wire Line
	10100 7100 10500 7100
Wire Wire Line
	10500 7200 10100 7200
Wire Wire Line
	10100 7300 10500 7300
Wire Wire Line
	10500 7400 10100 7400
Wire Wire Line
	10100 7500 10500 7500
$Comp
L Connector_Generic:Conn_01x04 J2
U 1 1 606F2829
P 2800 6000
F 0 "J2" H 2718 6317 50  0000 C CNN
F 1 "Conn_01x04" H 2718 6226 50  0000 C CNN
F 2 "Connector_JST:JST_PH_S4B-PH-SM4-TB_1x04-1MP_P2.00mm_Horizontal" H 2800 6000 50  0001 C CNN
F 3 "~" H 2800 6000 50  0001 C CNN
	1    2800 6000
	-1   0    0    -1  
$EndComp
$Comp
L power:GND #PWR0101
U 1 1 607B4E9C
P 3250 6300
F 0 "#PWR0101" H 3250 6050 50  0001 C CNN
F 1 "GND" H 3255 6127 50  0000 C CNN
F 2 "" H 3250 6300 50  0001 C CNN
F 3 "" H 3250 6300 50  0001 C CNN
	1    3250 6300
	1    0    0    -1  
$EndComp
Text Label 3500 6200 2    50   ~ 0
SCL_5V
$Comp
L MCU_RaspberryPi_and_Boards:Pico U1
U 1 1 6070D9B2
P 7000 5000
F 0 "U1" H 7000 6215 50  0000 C CNN
F 1 "Pico" H 7000 6124 50  0000 C CNN
F 2 "MCU_RaspberryPi_and_Boards:RPi_Pico_SMD_TH" V 7000 5000 50  0001 C CNN
F 3 "" H 7000 5000 50  0001 C CNN
	1    7000 5000
	1    0    0    -1  
$EndComp
$Comp
L power:GND #PWR0102
U 1 1 6070F461
P 7800 6050
F 0 "#PWR0102" H 7800 5800 50  0001 C CNN
F 1 "GND" H 7805 5877 50  0000 C CNN
F 2 "" H 7800 6050 50  0001 C CNN
F 3 "" H 7800 6050 50  0001 C CNN
	1    7800 6050
	1    0    0    -1  
$EndComp
$Comp
L power:GND #PWR0103
U 1 1 6070FB6A
P 6200 6050
F 0 "#PWR0103" H 6200 5800 50  0001 C CNN
F 1 "GND" H 6205 5877 50  0000 C CNN
F 2 "" H 6200 6050 50  0001 C CNN
F 3 "" H 6200 6050 50  0001 C CNN
	1    6200 6050
	1    0    0    -1  
$EndComp
Wire Wire Line
	7700 4250 7800 4250
Wire Wire Line
	7800 4250 7800 4750
Wire Wire Line
	7700 5250 7800 5250
Connection ~ 7800 5250
Wire Wire Line
	7800 5250 7800 5750
Wire Wire Line
	7700 5750 7800 5750
Connection ~ 7800 5750
Wire Wire Line
	7800 5750 7800 6050
Wire Wire Line
	6300 4250 6200 4250
Wire Wire Line
	6200 4250 6200 4750
Wire Wire Line
	6300 5750 6200 5750
Connection ~ 6200 5750
Wire Wire Line
	6200 5750 6200 6050
Wire Wire Line
	6300 5250 6200 5250
Connection ~ 6200 5250
Wire Wire Line
	6200 5250 6200 5750
Wire Wire Line
	6300 4750 6200 4750
Connection ~ 6200 4750
Wire Wire Line
	6200 4750 6200 5250
Wire Wire Line
	7700 4750 7800 4750
Connection ~ 7800 4750
Wire Wire Line
	7800 4750 7800 5250
$Comp
L power:GND #PWR0104
U 1 1 60717F85
P 7000 6250
F 0 "#PWR0104" H 7000 6000 50  0001 C CNN
F 1 "GND" H 7005 6077 50  0000 C CNN
F 2 "" H 7000 6250 50  0001 C CNN
F 3 "" H 7000 6250 50  0001 C CNN
	1    7000 6250
	1    0    0    -1  
$EndComp
Wire Wire Line
	7000 6150 7000 6250
Text Label 5900 4050 0    50   ~ 0
SDA_3V3
Text Label 5900 4150 0    50   ~ 0
SCL_3V3
Wire Wire Line
	5900 4150 6300 4150
Wire Wire Line
	6300 4050 5900 4050
$Comp
L Switch:SW_Push SW1
U 1 1 6071C67F
P 8550 5050
F 0 "SW1" H 8550 5335 50  0000 C CNN
F 1 "SW_Push" H 8550 5244 50  0000 C CNN
F 2 "Button_Switch_THT:SW_PUSH_6mm" H 8550 5250 50  0001 C CNN
F 3 "~" H 8550 5250 50  0001 C CNN
	1    8550 5050
	1    0    0    -1  
$EndComp
Wire Wire Line
	7800 5250 8850 5250
Wire Wire Line
	8850 5250 8850 5050
Wire Wire Line
	8850 5050 8750 5050
Wire Wire Line
	8350 5050 7700 5050
Text Label 5900 4350 0    50   ~ 0
Row_7
Text Label 5900 4450 0    50   ~ 0
Row_6
Text Label 5900 4550 0    50   ~ 0
Row_5
Text Label 5900 4650 0    50   ~ 0
Row_4
Wire Wire Line
	5900 4650 6300 4650
Wire Wire Line
	6300 4550 5900 4550
Wire Wire Line
	5900 4450 6300 4450
Wire Wire Line
	6300 4350 5900 4350
Text Label 8100 4650 2    50   ~ 0
Row_3
Text Label 5900 4850 0    50   ~ 0
Row_2
Text Label 8100 4850 2    50   ~ 0
Row_1
Text Label 5900 4950 0    50   ~ 0
Row_0
Wire Wire Line
	5900 4950 6300 4950
Wire Wire Line
	7700 4850 8100 4850
Wire Wire Line
	5900 4850 6300 4850
Wire Wire Line
	7700 4650 8100 4650
Text Label 8100 4950 2    50   ~ 0
Col_15
Text Label 5900 5050 0    50   ~ 0
Col_14
Text Label 5900 5150 0    50   ~ 0
Col_13
Text Label 8100 5150 2    50   ~ 0
Col_12
Wire Wire Line
	8100 4950 7700 4950
Wire Wire Line
	6300 5050 5900 5050
Wire Wire Line
	5900 5150 6300 5150
Wire Wire Line
	7700 5150 8100 5150
Text Label 5900 5350 0    50   ~ 0
Col_11
Text Label 8100 5350 2    50   ~ 0
Col_10
Wire Wire Line
	6300 5350 5900 5350
Wire Wire Line
	8100 5350 7700 5350
Text Label 5900 5450 0    50   ~ 0
Col_9
Wire Wire Line
	6300 5450 5900 5450
Text Label 8100 5450 2    50   ~ 0
Col_8
Wire Wire Line
	8100 5450 7700 5450
Text Label 5900 5550 0    50   ~ 0
Col_7
Wire Wire Line
	6300 5550 5900 5550
Text Label 8100 5550 2    50   ~ 0
Col_6
Wire Wire Line
	8100 5550 7700 5550
Text Label 5900 5650 0    50   ~ 0
Col_5
Wire Wire Line
	6300 5650 5900 5650
Text Label 8100 5650 2    50   ~ 0
Col_4
Wire Wire Line
	8100 5650 7700 5650
Text Label 5900 5850 0    50   ~ 0
Col_3
Wire Wire Line
	6300 5850 5900 5850
Text Label 8100 5850 2    50   ~ 0
Col_2
Wire Wire Line
	8100 5850 7700 5850
Text Label 5900 5950 0    50   ~ 0
Col_1
Wire Wire Line
	6300 5950 5900 5950
Text Label 8100 5950 2    50   ~ 0
Col_0
Wire Wire Line
	8100 5950 7700 5950
Wire Wire Line
	3000 5900 3250 5900
Wire Wire Line
	3250 5900 3250 6300
Text Label 8100 4050 2    50   ~ 0
VBus
Wire Wire Line
	8100 4050 7700 4050
Text Label 3500 6000 2    50   ~ 0
VBus
Wire Wire Line
	3000 6200 3500 6200
Text Label 3500 6100 2    50   ~ 0
SDA_5V
Wire Wire Line
	3000 6100 3500 6100
Wire Wire Line
	3000 6000 3500 6000
$Comp
L Device:R R3
U 1 1 607B724B
P 3700 5250
F 0 "R3" H 3770 5296 50  0000 L CNN
F 1 "10K" H 3770 5205 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 3630 5250 50  0001 C CNN
F 3 "~" H 3700 5250 50  0001 C CNN
	1    3700 5250
	1    0    0    -1  
$EndComp
$Comp
L Device:R R4
U 1 1 607B76D6
P 4300 5250
F 0 "R4" H 4370 5296 50  0000 L CNN
F 1 "10K" H 4370 5205 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 4230 5250 50  0001 C CNN
F 3 "~" H 4300 5250 50  0001 C CNN
	1    4300 5250
	1    0    0    -1  
$EndComp
Wire Wire Line
	4200 5500 4300 5500
Wire Wire Line
	4300 5500 4300 5400
Wire Wire Line
	3800 5500 3700 5500
Wire Wire Line
	3700 5500 3700 5400
Text Label 4600 5500 2    50   ~ 0
SDA_5V
Text Label 3400 5500 0    50   ~ 0
SDA_3V3
Wire Wire Line
	3400 5500 3700 5500
Connection ~ 3700 5500
Wire Wire Line
	3700 5100 3700 5000
Wire Wire Line
	3700 5000 4000 5000
Wire Wire Line
	4000 5000 4000 5200
Text Label 4600 5000 2    50   ~ 0
VBus
Wire Wire Line
	4600 5000 4300 5000
Wire Wire Line
	4300 5000 4300 5100
Wire Wire Line
	4600 5500 4300 5500
Connection ~ 4300 5500
Text Label 8100 4150 2    50   ~ 0
3V3
Wire Wire Line
	8100 4150 7700 4150
Text Label 3400 5000 0    50   ~ 0
3V3
Wire Wire Line
	3400 5000 3700 5000
Connection ~ 3700 5000
$Comp
L Device:R R1
U 1 1 607D2FC7
P 3700 4500
F 0 "R1" H 3770 4546 50  0000 L CNN
F 1 "10K" H 3770 4455 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 3630 4500 50  0001 C CNN
F 3 "~" H 3700 4500 50  0001 C CNN
	1    3700 4500
	1    0    0    -1  
$EndComp
$Comp
L Device:R R2
U 1 1 607D2FD1
P 4300 4500
F 0 "R2" H 4370 4546 50  0000 L CNN
F 1 "10K" H 4370 4455 50  0000 L CNN
F 2 "Resistor_SMD:R_0603_1608Metric" V 4230 4500 50  0001 C CNN
F 3 "~" H 4300 4500 50  0001 C CNN
	1    4300 4500
	1    0    0    -1  
$EndComp
Wire Wire Line
	4200 4750 4300 4750
Wire Wire Line
	4300 4750 4300 4650
Wire Wire Line
	3800 4750 3700 4750
Wire Wire Line
	3700 4750 3700 4650
Text Label 4600 4750 2    50   ~ 0
SCL_5V
Text Label 3400 4750 0    50   ~ 0
SCL_3V3
Wire Wire Line
	3400 4750 3700 4750
Connection ~ 3700 4750
Wire Wire Line
	3700 4350 3700 4250
Wire Wire Line
	3700 4250 4000 4250
Wire Wire Line
	4000 4250 4000 4450
Text Label 4600 4250 2    50   ~ 0
VBus
Wire Wire Line
	4600 4250 4300 4250
Wire Wire Line
	4300 4250 4300 4350
Wire Wire Line
	4600 4750 4300 4750
Connection ~ 4300 4750
Text Label 3400 4250 0    50   ~ 0
3V3
Wire Wire Line
	3400 4250 3700 4250
Connection ~ 3700 4250
$Comp
L Transistor_FET:BSS138 Q2
U 1 1 607D9B99
P 4000 5400
F 0 "Q2" V 4249 5400 50  0000 C CNN
F 1 "BSS138" V 4340 5400 50  0000 C CNN
F 2 "Package_TO_SOT_SMD:SOT-23" H 4200 5325 50  0001 L CIN
F 3 "https://www.onsemi.com/pub/Collateral/BSS138-D.PDF" H 4000 5400 50  0001 L CNN
	1    4000 5400
	0    1    1    0   
$EndComp
$Comp
L Transistor_FET:BSS138 Q1
U 1 1 607E126D
P 4000 4650
F 0 "Q1" V 4249 4650 50  0000 C CNN
F 1 "BSS138" V 4340 4650 50  0000 C CNN
F 2 "Package_TO_SOT_SMD:SOT-23" H 4200 4575 50  0001 L CIN
F 3 "https://www.onsemi.com/pub/Collateral/BSS138-D.PDF" H 4000 4650 50  0001 L CNN
	1    4000 4650
	0    1    1    0   
$EndComp
$EndSCHEMATC
